RockTimeWebsite/Models/ArticleViewModel.cs
using Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RockTimeWebsite.Models
{
    public class ArticleViewModel
    {
        public Article Article { get; set; }
    }
}

RockTimeWebsite/Controllers/ArticleController.cs
using DataLayer.Concrete;
using DataLayer.Entities;
using Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RockTimeWebsite.Controllers
{
    public class ArticleController : Controller
    {
        public PartialViewResult Index(int? pageId)
        {
            using (IRepository<Article> repository = new ArticleRepository())
            {
                if (pageId != null)
                    return PartialView(repository.Find(Convert.ToInt16(pageId)));
                else
                    return PartialView(new Article {
                        ArticleTitle="No article has been found",
                        ArticleHeader = "No article has been found!",
                        ArticleLevel = 2,
                        ArticleContent = "",
                        ParentArticleId = 0
                    });
            }
        }
        [HttpGet]
        public ViewResult Edit(int articleId, int parentArticleId)
        {
            if(articleId!=0)
            {
                using (IRepository<Article> repository = new ArticleRepository())
                {
                    var article = repository.Find(articleId);
                    ViewBag.EditorTitle = article.ArticleTitle; 
                    return View(article); 
                }
            }
            else
            {
                ViewBag.EditorTitle = "Add New Article"; 
                return View(new Article {
                    ParentArticleId = parentArticleId,
                    ArticleLevel = 2
                });
            }    
        }
        [HttpPost]
        public ActionResult Edit(Article article)
        {
            bool isSaved = false;
            if (ModelState.IsValid)
            {
                using (IRepository<Article> repository = new ArticleRepository())
                {
                    repository.InsertOrUpdate(article);
                    isSaved = repository.Save();
                }
            }
            if (isSaved)
            {
                TempData["EditorMessage"] =  "Article " + article.ArticleTitle + " Was Successfully Updated!";
                TempData["MessageType"] = 1;
            }   
            else
            {
                TempData["EditorMessage"] = "Problem saving data!";
                TempData["MessageType"] = 0;
            }
            return RedirectToAction("Index", "Home", null); 
        }
        public ActionResult Delete(int articleId)
        {
            bool isDeleted = false;
            using (IRepository<Article> repository = new ArticleRepository())
            {
                var article = repository.Find(articleId);
                repository.Delete(article);
                isDeleted = repository.Save();
            }
            if(isDeleted)
            {
                TempData["EditorMessage"] = "Article Was Removed From The Database!";
                TempData["MessageType"] = 1;
            }
            else
            {
                TempData["EditorMessage"] = "Can't Delete Data!";
                TempData["MessageType"] = 0;
            }
            return RedirectToAction("Index", "Home", null);
        }

    }
}

RockTimeWebsite/Controllers/HeaderController.cs
using DataLayer.Concrete;
using DataLayer.Entities;
using Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RockTimeWebsite.Controllers
{
    public class HeaderController : Controller
    {
        public PartialViewResult Index(string catchall)
        {
            using(IRepository<Article> repository = new ArticleRepository())
            {
                ViewBag.SelectedPage = catchall;
                return PartialView(repository.All.ToList().Where(a => a.ArticleLevel == 1).ToList());
            }
        }

    }
}

RockTimeWebsite/Controllers/HomeController.cs
using DataLayer.Concrete;
using DataLayer.Entities;
using Domain;
using RockTimeWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RockTimeWebsite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (TempData["EditorMessage"] != null)
            {
                ViewBag.EditorMessage = TempData["EditorMessage"];
                ViewBag.MessageType = TempData["MessageType"];
            }
            using (IRepository<Article> repository = new ArticleRepository())
            {
                ArticleViewModel model = new ArticleViewModel
                {
                    Article = repository.Default
                };
                return View(model);
            }
        }
    }
}

RockTimeWebsite/Views/Article/Edit.cshtml
@model Article
<article class="panel panel-default">
    <h2 class="panel-heading em10">
        <span>@ViewBag.EditorTitle</span>
    </h2>
    @using (Html.BeginForm("Edit", "Article"))
    {   <div class="panel-body em8">
            <div class="form-group form-group-sm">
                <label for="usr">Article Title:</label>
                <input type="text" name="ArticleTitle" value="@Model.ArticleTitle" class="form-control em8" placeholder="Article Title">
            </div>
            <div class="form-group form-group-sm">
                <label for="usr">Article Header:</label>
                <input type="text" name="ArticleHeader" value="@Model.ArticleHeader" class="form-control em8" placeholder="Article Header">
            </div>
            <div class="form-group form-group-sm">
                <label for="usr">Article Content:</label>
                <textarea name="ArticleContent" class="form-control em8">@Model.ArticleContent</textarea>
            </div>
            <input type="hidden" value="@Model.ArticleId" name="ArticleId">
            <input type="hidden" value="@Model.ParentArticleId" name="ParentArticleId">
            <input type="hidden" value="@Model.ArticleLevel" name="ArticleLevel">
        </div>
        <footer class="panel-footer">
            <div class="text-right">
                <button class="btn btn-danger btn-sm" type="submit">Save</button>
            </div>
        </footer>
    }
</article>

RockTimeWebsite/Views/Article/Index.cshtml
@model Article
<article class="panel panel-default">
    <h2 class="panel-heading em10">
        <span>@Model.ArticleTitle</span>
    </h2>
    <p class="panel-body em8">
        @Model.ArticleContent
    </p>
    <footer class="panel-footer">
        <div class="text-right">

            <button class="btn btn-danger btn-sm em7" type="button" onclick="$.colorbox({href:'@Url.Action("Edit", "Article",
            new { articleId = @Model.ArticleId , parentArticleId = @Model.ParentArticleId })', transition: 'elastic',  overlayClose: true, width: '80%', height: '70%'});">Edit</button>
            
            @Html.RouteLink("Delete Article",
            new {
            controller = "Article",
            action = "Delete",
            articleId = Model.ArticleId
            },
            new
            {
                @class = "btn btn-danger btn-sm em7"
            })

        </div>
    </footer>
</article>

RockTimeWebsite/Views/Header/Index.cshtml
@model List<Article>
<header id="mainHeader" class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="/home" class="navbar-brand">
                <h1 class="strip-pm em11">rocktime</h1>
                <p class="strip-pm em7">The Company That Rocks</p>
            </a>
        </div>
        <nav>
            <ul class="nav navbar-nav">
                @foreach (var item in Model)
                {
                    string currentPage = ViewBag.SelectedPage;
                    <li class="@(currentPage == item.ArticleTitle.ToUrl() ? "active" : "inact") dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="/@item.ArticleTitle.ToUrl()"
                           title="@item.ArticleTitle" role="button" aria-haspopup="true">
                            @item.ArticleTitle
                        </a>
                        @if (item.Articles.Count() > 0)
                        {
                            <ul class="dropdown-menu">
                                @foreach (var art in item.Articles)
                                {
                                    <li>
                                        <a href="/@art.ArticleTitle.ToUrl()" title="/@art.ArticleTitle">@art.ArticleTitle</a>
                                    </li>
                                }
                            </ul>
                        }
                        </li>
                }
                <li><a href="/about-us" title="About The Company">About Us</a></li>
                <li><a href="/contact-us" title="Conatct Rocktime">Contact Us</a></li>
            </ul>
        </nav>
    </div>
</header>

RockTimeWebsite/Views/Home/Index.cshtml
@model ArticleViewModel

@{
    var page = Model.Article;
    var articles = page.Articles;
}

@{
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<main id="rocktime-main">
    <div class="container-fluid col-lg-10 col-lg-offset-1">
        <header id="mainHeader" class="page-header">
            <h2 class="em13">@page.ArticleHeader</h2>
        </header>
        <section>
            <h3 class="em12">List Of Current Articles</h3>
            @if (ViewBag.MessageType != null)
            {
                <p class="alert @( ViewBag.MessageType == 1 ? "alert-success" : "alert-danger")">@ViewBag.EditorMessage</p>
            }
            @foreach (var article in articles)
            {
                <article class="panel panel-default">
                    <h3 class="panel-heading em10">
                        <span>@article.ArticleTitle</span>
                    </h3>
                    <p class="panel-body em8">
                        @article.ArticleContent.Substring(0, @article.ArticleContent.Length/3)...
                    </p>
                    <footer class="panel-footer">
                        <div class="text-right">
                            <a href="/home/article?pageId=@article.ArticleId" title="@article.ArticleTitle" class="iframe cboxElement btn btn-danger btn-sm em7">View Article</a>
                            <button class="btn btn-danger btn-sm em7" type="button" onclick="$.colorbox({href:'@Url.Action("Edit", "Article",
                            new { articleId = 0 , parentArticleId = @page.ArticleId })', transition: 'elastic',  overlayClose: true, width: '80%', height: '70%'});">Add New Article</button>
                        </div>
                    </footer>
                </article>
            }
        </section>
    </div>
</main>
@section scripts {
<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script src="~/Scripts/jquery.colorbox-min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script>
    jQuery('a.iframe').colorbox({ width: '70%', 'height': '50%', title: false, transition: 'elastic', overlayClose: true });
</script>
}

RockTimeWebsite/Views/Shared/_Footer.cshtml
<div class="clearfix"></div>
<footer id="pageFooter" role="contentinfo">
    <div class="container-fluid col-lg-10 col-lg-offset-1 em8">
        <div class="col-md-6 strip-pm">
            <p class="strip-pm"><a href="tel://000-777-888-999" title="Call Us">Telephone: 000777888999</a></p>
            <p><a href="mailto:me@somewhere.com" title="Email Us">Email: me@somewhere.com</a></p>
        </div>
        <div class="col-md-6 strip-pm text-right">
            <p><b>Rocktime</b></p>
            <p>
                15 Factory Road, Upton<br>
                Poole, Dorset BH16 5SN
            </p>
            <p>
                000-777-888-999<br>
                000-777-777-777 <i>(when we are very busy)</i>
            </p>
            <p><small>&copy;copyright 2016 Rocktime  | <a href="#">Terms &amp; Conditions</a></small> </p>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</footer>

RockTimeWebsite/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/colorbox.css" rel="stylesheet" />
</head>

<body>
    @{ Html.RenderAction("Index", "Header", new { catchall = "home" } ); }
    @RenderBody()
    @Html.Partial("_Footer")
  
    @RenderSection("scripts", required: false)
</body>
</html>